export const generateMockSites = () => {
  const now = new Date();
  const minutesAgo = (minutes) => new Date(now.getTime() - minutes * 60000);

  return [
    {
      id: '1',
      url: 'example.com',
      name: 'Example Site',
      addedDate: new Date('2024-01-15'),
      trackedPixels: {
        gtm: { enabled: true, containerId: 'GTM-XXXX' },
        ga4: { enabled: true, measurementId: 'G-XXXX' },
        meta: { enabled: true, pixelId: '123456789' },
        xandr: { enabled: false, pixelId: '' },
        simplifi: { enabled: false, pixelId: '' },
      },
      status: {
        gtm: 'active',
        ga4: 'active',
        meta: 'active',
        xandr: 'missing',
        simplifi: 'missing',
      },
      lastSeen: minutesAgo(2),
      notes: 'All systems operational',
      consentStatus: 'granted',
    },
    {
      id: '2',
      url: 'clientsite.co',
      name: 'Client Website',
      addedDate: new Date('2024-02-20'),
      trackedPixels: {
        gtm: { enabled: true, containerId: 'GTM-ABC123' },
        ga4: { enabled: true, measurementId: 'G-ABC123' },
        meta: { enabled: true, pixelId: '987654321' },
        xandr: { enabled: true, pixelId: 'XND-12345' },
        simplifi: { enabled: false, pixelId: '' },
      },
      status: {
        gtm: 'active',
        ga4: 'missing',
        meta: 'active',
        xandr: 'blocked',
        simplifi: 'missing',
      },
      lastSeen: minutesAgo(15),
      notes: 'GA4 configuration issue',
      consentStatus: 'pending',
    },
    {
      id: '3',
      url: 'shopify-store.com',
      name: 'E-commerce Store',
      addedDate: new Date('2024-03-10'),
      trackedPixels: {
        gtm: { enabled: true, containerId: 'GTM-DEF456' },
        ga4: { enabled: true, measurementId: 'G-SHOP789' },
        meta: { enabled: true, pixelId: '555444333' },
        xandr: { enabled: false, pixelId: '' },
        simplifi: { enabled: true, pixelId: 'SF-98765' },
      },
      status: {
        gtm: 'active',
        ga4: 'active',
        meta: 'blocked',
        xandr: 'missing',
        simplifi: 'active',
      },
      lastSeen: minutesAgo(5),
      notes: 'Ad blocker affecting Meta',
      consentStatus: 'granted',
    },
    {
      id: '4',
      url: 'portfolio-site.dev',
      name: 'Portfolio Website',
      addedDate: new Date('2024-04-01'),
      trackedPixels: {
        gtm: { enabled: true, containerId: 'GTM-PORT99' },
        ga4: { enabled: true, measurementId: 'G-PORT123' },
        meta: { enabled: false, pixelId: '' },
        xandr: { enabled: false, pixelId: '' },
        simplifi: { enabled: false, pixelId: '' },
      },
      status: {
        gtm: 'missing',
        ga4: 'missing',
        meta: 'missing',
        xandr: 'missing',
        simplifi: 'missing',
      },
      lastSeen: minutesAgo(60),
      notes: 'Site under maintenance',
      consentStatus: 'granted',
    },
    {
      id: '5',
      url: 'corporate-website.com',
      name: 'Corporate Site',
      addedDate: new Date('2024-01-30'),
      trackedPixels: {
        gtm: { enabled: true, containerId: 'GTM-CORP999' },
        ga4: { enabled: true, measurementId: 'G-CORP123' },
        meta: { enabled: true, pixelId: '111222333' },
        xandr: { enabled: true, pixelId: 'XND-CORP1' },
        simplifi: { enabled: true, pixelId: 'SF-CORP2' },
      },
      status: {
        gtm: 'active',
        ga4: 'active',
        meta: 'active',
        xandr: 'active',
        simplifi: 'active',
      },
      lastSeen: minutesAgo(0.5),
      notes: 'High traffic site',
      consentStatus: 'pending',
    },
  ];
};